## Global Variabel
#@BaseUrl = https://pam-2026-p4-ifs23038-be.samuelsbrn.site:8080/
@BaseUrl = http://127.0.0.1:8000

## Profile
## ===========================================

### Mengambil semua data tumbuhan
# @name GetProfile
GET {{BaseUrl}}/profile
Content-Type: application/json

### Mengambil photo profil
# @name GetProfilePhoto
GET {{BaseUrl}}/profile/photo
Content-Type: application/json


## Plants
## ===========================================

### Mengambil semua data tumbuhan
# @name GetAllPlants
GET {{BaseUrl}}/plants?search=
Content-Type: application/json

#> {%
#    client.global.set("plantId", response.body.data.plants[0].id);
#    console.log(client.global.get("plantId"))
#%}

### Menambahkan data tumbuhan baru
# @name PostPlants
POST {{BaseUrl}}/plants
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nama"

Kangkung
--WebAppBoundary
Content-Disposition: form-data; name="deskripsi"

Brokoli adalah sayuran hijau yang kaya vitamin, mineral, dan serat
--WebAppBoundary
Content-Disposition: form-data; name="manfaat"

Membantu detoksifikasi dan menjaga kesehatan mata
--WebAppBoundary
Content-Disposition: form-data; name="efekSamping"

Dapat menyebabkan kembung
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="example.png"
Content-Type: image/png

< ./example.png
--WebAppBoundary--

> {%
    client.global.set("plantId", response.body.data.plantId);
    console.log(client.global.get("plantId"))
%}

### Mengambil data tumbuhan berdasarkan id-nya
# @name GetPlantById
GET {{BaseUrl}}/plants/{{plantId}}
Content-Type: application/json

### Melihat gambar tumbuhan
# @name GetPlantImageById
GET {{BaseUrl}}/plants/{{plantId}}/image
Content-Type: application/json

### Mengubah hanya data plant berdasarkan id-nya
# @name PutPlantOnlyData
PUT {{BaseUrl}}/plants/{{plantId}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nama"

Brokoli Update
--WebAppBoundary
Content-Disposition: form-data; name="deskripsi"

Brokoli adalah sayuran hijau yang kaya vitamin, mineral, dan serat
--WebAppBoundary
Content-Disposition: form-data; name="manfaat"

Membantu detoksifikasi dan menjaga kesehatan mata
--WebAppBoundary
Content-Disposition: form-data; name="efekSamping"

Dapat menyebabkan kembung
--WebAppBoundary--

### Mengubah gambar dan data plant berdasarkan id-nya
# @name PutPlant
PUT {{BaseUrl}}/plants/{{plantId}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nama"

Brokoli
--WebAppBoundary
Content-Disposition: form-data; name="deskripsi"

Brokoli adalah sayuran hijau yang kaya vitamin, mineral, dan serat
--WebAppBoundary
Content-Disposition: form-data; name="manfaat"

Membantu detoksifikasi dan menjaga kesehatan mata
--WebAppBoundary
Content-Disposition: form-data; name="efekSamping"

Dapat menyebabkan kembung
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="example.png"
Content-Type: image/png

< ./example.png
--WebAppBoundary--

### Menghapus data plant berdasarkan id-nya
# @name DeletePlant
DELETE {{BaseUrl}}/plants/{{plantId}}
Content-Type: application/json

## Motors
## ===========================================

### Mengambil semua data motor
# @name GetAllMotors
GET {{BaseUrl}}/motors?search=
Content-Type: application/json

#> {%
#    client.global.set("motorId", response.body.data.motors[0].id);
#    console.log(client.global.get("motorId"))
#%}


### Menambahkan data motor baru
### Tambah Motor Baru
POST {{BaseUrl}}/motors
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nama"

Honda CBR 150R
--WebAppBoundary
Content-Disposition: form-data; name="deskripsi"

Motor sport 150cc dengan desain aerodinamis dan performa tinggi
--WebAppBoundary
Content-Disposition: form-data; name="spesifikasi"

Mesin 149.16 cc DOHC 4-Katup, Liquid Cooled, Transmisi 6-Kecepatan
--WebAppBoundary
Content-Disposition: form-data; name="harga"

37000000
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="R15.jpg"
Content-Type: image/jpeg

< ./R15.jpg
--WebAppBoundary--

> {%
    client.global.set("motorId", response.body.data.motorId);
    console.log(client.global.get("motorId"))
%}


### Mengambil data motor berdasarkan id
# @name GetMotorById
GET {{BaseUrl}}/motors/{{motorId}}
Content-Type: application/json


### Melihat gambar motor
# @name GetMotorImageById
GET {{BaseUrl}}/motors/{{motorId}}/image
Content-Type: application/json


### Mengubah hanya data motor (tanpa gambar)
# @name PutMotorOnlyData
PUT {{BaseUrl}}/motors/{{motorId}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nama"

Honda CBR 150R Update
--WebAppBoundary
Content-Disposition: form-data; name="deskripsi"

Motor sport 150cc dengan desain aerodinamis dan performa tinggi
--WebAppBoundary
Content-Disposition: form-data; name="manfaat"

Cocok untuk perjalanan jauh dan penggunaan harian
--WebAppBoundary
Content-Disposition: form-data; name="efekSamping"

Biaya perawatan relatif lebih mahal
--WebAppBoundary--


### Mengubah data dan gambar motor
# @name PutMotor
PUT {{BaseUrl}}/motors/{{motorId}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nama"

Yamaha R15
--WebAppBoundary
Content-Disposition: form-data; name="deskripsi"

Motor sport dengan fitur modern dan teknologi VVA
--WebAppBoundary
Content-Disposition: form-data; name="manfaat"

Performa stabil di kecepatan tinggi
--WebAppBoundary
Content-Disposition: form-data; name="efekSamping"

Posisi duduk kurang nyaman untuk perjalanan sangat jauh
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="example.png"
Content-Type: image/png

< ./example.png
--WebAppBoundary--


### Menghapus data motor berdasarkan id
# @name DeleteMotor
DELETE {{BaseUrl}}/motors/{{motorId}}
Content-Type: application/json